global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:

  - job_name: 'prometheus-demo'

    scrape_interval: 2s
    scrape_timeout: 1s
    metrics_path: '/prometheus-metrics'

    static_configs:
     - targets: ['localhost:8081']